apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qwujqftrx-go 
  janus-idp.io/tekton: qwujqftrx-go
  backstage.io/kubernetes-id: qwujqftrx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qwujqftrx-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  